# Generated by Django 4.1.1 on 2023-01-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_applicationuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
