# Generated by Django 4.1.5 on 2023-01-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpCode', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
